Repository errbit/errbit, pull requests merged in 2018-07, with the labels that each got.

#1278 Upgrade Mongoid to 5.4 to support MongoDB 3.6
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  app/models/app.rb
Labels: maintenance

#1279 README: remove gemnasium
  README.md
Labels: maintenance

#1213 Apply system timezone to slack notification
  app/models/notification_services/slack_service.rb
  spec/models/notification_service/slack_service_spec.rb
Labels: feature

#1282 Heroku review app: use a fixed admin email/password for easier review
  app.json
Labels: maintenance

#1283 README: Pull out some old upgrade information
  README.md
  docs/upgrading.md
Labels: documentation

#1281 CI: require ruby 2.5 passing
  .travis.yml
  README.md
Labels: maintenance

#1304 Implement /health/readiness without using Timeout.timeout
  app/controllers/health_controller.rb
  spec/requests/health_controller_spec.rb
Labels: maintenance

#1309 Chore/update rubocop to 0.58.1
  .rubocop_todo.yml
  Gemfile.lock
  app/views/problems/_list.atom.builder
Labels: maintenance

#1303 docker-compose: bump mongodb version from 3.4 to 4.0
  docker-compose.yml
Labels: maintenance

#1311 Rails: eager-load all of lib/
  config/application.rb
Labels: bug

#1272 GitHub Auth: Show error msg on empty email
  app/controllers/users/omniauth_callbacks_controller.rb
  spec/controllers/users/omniauth_callbacks_controller_spec.rb
Labels: feature

#1302 Remove capistrano as a supported deploy mechanism
  Gemfile
  Gemfile.lock
  config/deploy.example.rb
  docs/deployment.md
  docs/deployment/capistrano.md
Labels: maintenance

#1312 Rails 4.2.9 to 4.2.10 upgrade
  Gemfile
  Gemfile.lock
Labels: maintenance

#1316 Fix specs on ruby 2.6.x
  app/models/notice.rb
Labels: maintenance

#1326 CI: cache rubocop re-run optimization and mongodb install file
  .travis.yml
Labels: maintenance

#1328 Spec: Fix SimpleCov::Formatter::MultiFormatter warning
  spec/spec_helper.rb
Labels: maintenance

#1334 Gemfile: allow test gems to be upgraded as appropriate
  Gemfile
  Gemfile.lock
Labels: maintenance

#1337 user#edit: remove duplicate error output
  app/views/users/edit.html.haml
Labels: bug
