Repository errbit/errbit, pull requests merged in 2018-08, with the labels that each got.

#1336 Heroku deploy: add demo data too
  app.json
  db/seeds.rb
  docs/configuration.md
Labels: maintenance

#1344 Remove gem rspec-its dependency
  Gemfile
  Gemfile.lock
  spec/models/error_report_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#1346 Heroku: upgrade from ruby 2.3.3 to 2.5.1
  app.json
  docs/deployment/dokku.md
  docs/deployment/heroku.md
Labels: maintenance

#1345 Update kaminari to 1.1 series
  Gemfile
  Gemfile.lock
Labels: maintenance

#1315 Sparklines with ajax and rubocop clean
  app/assets/stylesheets/errbit.css.erb
  app/controllers/problems_controller.rb
  app/models/problem.rb
  app/views/notices/_summary.html.haml
  app/views/problems/_sparkline.html.haml
  config/locales/en.yml
  config/routes.rb
  lib/sparklines.rb
  spec/controllers/problems_controller_spec.rb
  spec/lib/sparklines_spec.rb
  spec/models/problem_spec.rb
Labels: feature

#1354 add /problems?exclude_apps=app1,app2 feature
  .rubocop_todo.yml
  app/controllers/problems_controller.rb
  app/models/problem.rb
  docs/apps.md
  spec/models/problem_spec.rb
Labels: feature

#1361 Ensure user_attributes returns a Hash
  lib/airbrake_api/v3/notice_parser.rb
  spec/lib/airbrake_api/v3/notice_parser_spec.rb
Labels: bug
